config/routes.rb
Rails.application.routes.draw do
  # ORDER MATTERS 
  resources :users
  resources :games do
    resources :runs
  end

  #user index stuff
  get '/usersplaygames', to: 'games#userindex'
  get '/usersindex', to: 'users#index', as: "userindex"

  #login stuff
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'postsignup'
  get 'login', to: 'users#login'
  post 'login', to: 'users#postlogin', as: 'postlogin'
  get 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#oauthcreate' 

  # This redirects *most* broken paths to the default /games, which is the index
  get '*path', to: redirect('/games') 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :runs
  has_many :users, through: :runs
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :game, required: false
  belongs_to :user
  validates :hour, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 23 }, allow_blank: true
  validates :minute, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 59 }
  validates :second, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 59 }

  def add_zero
    if self.minute.length == 1
      self.minute = "0"+self.minute
    end
    if self.second.length == 1
      self.second = "0"+self.second
    end
  end


  def time_formatting
    if ((self.hour == 0) || (self.hour == ""))
      return self.minute.to_s + ":" + self.second.to_s
    else
      return self.hour.to_s + ":" + self.minute.to_s + ":" + self.second.to_s
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_confirmation_of :password
  validates :name, :uniqueness => true, length: { in: 4..16 }
  has_many :runs
  has_many :games, through: :runs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController #all routes edited
  def new
    @game = Game.new
    render template: 'runs/new'
  end

  def create
  end

  def index
    @game = Game.all
  end

  def userindex
    params[:game] #user searched game
    @game = Game.where('lower(name) LIKE ?', "%#{params[:game].downcase}%").first
    if @game != nil
      @gameplayers = @game.users.uniq
    else
      flash[:notice] = "No search results found for '" + params[:game] + "'!"
      redirect_to games_path
    end
  end



  def show
    redirect_to game_runs_path(params[:id]) #This brings it to /games/:id/runs instead of /games/:id
  end

  def edit
    @run = Run.find(params[:id])
    @run.errors = nil
    render template: 'runs/edit'
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController #all routes edited

  
  def new
    @game = Game.find_by_id(params[:game_id])
    @allgames = Game.all
    if (@game != nil)
      @run = Run.new(game_id: params[:game_id])
    else
      redirect_to games_path
    end
  end

  def update
    @run = Run.find(params[:id])
    @run.update(hour: run_params['hour'], minute: run_params['minute'], second: run_params['second'])
    @run.save
    redirect_to game_runs_path(@run.game_id)
  end

  def edit
    @run = Run.find_by_id(params[:id])
    @game = Game.find_by_id(params[:game_id])
    if (@game != nil)
      if @game.id.to_i != @run.game_id.to_i
        redirect_to games_path #basically so you can't edit invalid runs / runs that don't exist
      else
        if @run.user_id.to_i != session[:user_id]
          redirect_to games_path #redirects if you are not the owner of the run
        end
                #success if neither of the above fail, brings you to EDIT RUN page
      end
    else
      redirect_to games_path
    end
  end

  def create
    @run = Run.new(run_params)
    @game = Game.find_by_id(run_params[:game_id])
    if @run.valid? == false
      render 'new'
    else
      @run.add_zero
      if !@run.save
        redirect_to game_runs_path(@run.game_id)
      else
        @run.save
        redirect_to game_runs_path(@run.game_id)
      end
    end
  end

  def index
    @game = Game.find_by_id(params[:game_id])
    @gamesorted = @game.runs.order(:hour).order(:minute).order(:second)
    if @game == nil
      redirect_to games_path
    end
  end

  def destroy
    @run = Run.find_by_id(params[:id])
    @game = Game.find_by_id(params[:game_id])
    if (@run != nil)
      if @game.id.to_i != @run.game_id.to_i
        redirect_to games_path #basically so you can't delete runs that don't exist
      else
        if @run.user_id.to_i != session[:user_id]
          redirect_to games_path #redirects if you are not the owner of the run
        end
        Run.find(params[:id]).destroy
        redirect_to game_runs_path(params[:game_id])
      end
    else
      redirect_to games_path
    end

    
  end


  private

  def run_params
    params.require(:run).permit(:hour, :second, :minute, :game_id, :user_id)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController #all routes edited

  def destroy
    session.delete :user_id
    redirect_to games_path
  end

  def create
    @user = User.find_by(name: params[:name])
    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to games_path
    else
      flash[:notice] = "ERROR: Couldn't log in, please try again!"
      redirect_to login_path
    end
  end

  def oauthcreate
    @user = User.find_by(uid: auth['uid'])
    if @user == nil  #if it didn't find a user, it will create a new one
      @user = User.new(name: auth['extra']['id_info']['name'], uid: auth['uid'], password: SecureRandom.hex(12))
      if @user.save
        session[:user_id] = @user.id
        redirect_to games_path
      else
        yo dude idk #if this fails i legit have no idea how to solve it
      end
    else  #if it does find a user, it assumes all is correct 
      session[:user_id] = @user.id
      redirect_to games_path
    end
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController #most routes edited

  def new 
    @user = User.new
  end

  def create
    tempuser = User.find_by(name: user_params[:name])
    @user = User.create(user_params)
    if tempuser == nil
      if user_params[:password] != user_params[:password_confirmation]
        flash[:notice] = "Passwords did not match, please try again!"
        render :new
        return
      end
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to games_path
      else
        flash[:notice] = "Database error, please try again later!"
        render :new
      end 
    else
      flash[:notice] = "Username " + user_params[:name] + " already taken, please try again!"
      render :new
      return
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user == nil
      redirect_to games_path
    end
  end

  def login
    @user = User.new
  end

  def postlogin
    @user = User.find_by(name: params[:name])
    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to games_path
    else
      if @user == nil
        flash[:notice] = "ERROR: Username not found!"
        render :login
      else

        flash[:notice] = "ERROR: Incorrect password!"
        render :login
      end
    end
  end

  def index
    @user = User.all
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation) #I forgot password_confirmation
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    !!session[:user_id]
  end
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/games/index.html.erb
<%= render '/layouts/header'%>
<% if flash[:notice] %>
  <br><h4><%= flash[:notice] %></h4>
  <% flash[:notice] = nil %>
<% end %>

<h3>Games Supported by our Leaderboard Website:</h3>

<h5>Search for all users who have played a specific game!</h5>
<%= form_tag('/usersplaygames', method: :get) do %>
  Game: <%= text_field_tag :game %>
  <%= submit_tag "Search!"%><br>
<% end %>

<% @game.each do |x| %>
  <%= link_to x.name, game_runs_path(x.id) %> <br>
<% end %>
<br>
<%= link_to "User Index", userindex_url %>

app/views/games/userindex.html.erb
<%= render '/layouts/header'%>
<h2>Users who have ran <%= @game.name %>:</h2>


<% @gameplayers.each do |x|%>
  <%= link_to x.name, user_path(x)%><br>
<% end %>

app/views/layouts/_header.html.erb
<% if session[:user_id] %>
  <%= link_to "Game index", games_path%>    <%= link_to "Logout", logout_url%> 
<% else %>
  <%= link_to "Game index", games_path%>    <%= link_to "Signup", signup_url%>    <%= link_to "Login", login_url%>    <%= link_to "Google Login", '/auth/google_oauth2', method: :post%>
<% end %>

app/views/layouts/_runform.html.erb
<%= form_for @run, url: createrun_url do |f| %>
  <%= f.hidden_field :game_id, :value => params[:id] %>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>
  <label>Hour: </label>
  <%= f.number_field :hour, in: 0..23, step: 1 %><br>
  <label>Minute: </label>
  <%= f.number_field :minute, in: 0..59, step: 1 %><br>
  <label>Second: </label>
  <%= f.number_field :second, in: 0..59, step: 1 %>

  <%= f.submit %>

<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leaderboardv2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/runs/edit.html.erb
<%= render '/layouts/header'%>
<h2>Edit your run:</h2>
  


<%= form_for [@game, @run] do |f| %>

  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@run.errors.count, "error") %> prohibited this run from being updated:</h4>

      <ul>
        <% @run.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :game_id, :value => params[:game_id] %>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>
  <label>Hour: </label>
  <%= f.number_field :hour, in: 0..23, step: 1 %><br>
  <label>Minute: </label>
  <%= f.number_field :minute, in: 0..59, step: 1 %><br>
  <label>Second: </label>
  <%= f.number_field :second, in: 0..59, step: 1 %><br>

  <%= f.submit %>
  <%=   link_to("Delete Run", [@game, @run], method: :delete) %>

<% end%>

app/views/runs/index.html.erb
<%= render '/layouts/header'%>
<h3>The <%=@game.name %> Leaderboard</h3>
<% if session[:user_id] %>
  <%= link_to "Submit a run here!", new_game_run_path %><br><br>
<% end %>

<% i=1 %>
<% @gamesorted.each do |x|%>
  <% if x.user.id == session[:user_id] %>
    <%= i %>. <%= link_to x.user.name, user_path(x.user)%> <%= x.time_formatting %> <%= link_to "Edit run", edit_game_run_path(:id => x.id) %> <br>
    <% i+=1 %>
  <% else %>
    <%= i %>. <%= link_to x.user.name, user_path(x.user)%> <%= x.time_formatting %><br>
    <% i+=1 %>
  <% end %>
<% end %>

app/views/runs/new.html.erb
<%= render '/layouts/header'%>
<h2>Submit a new run:</h2>



<%= form_for [@game, @run] do |f| %>

  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@run.errors.count, "error") %> prohibited this run from being created:</h4>

      <ul>
        <% @run.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :game_id %>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>
  <label>Hour: </label>
  <%= f.number_field :hour, in: 0..23, step: 1 %><br>
  <label>Minute: </label>
  <%= f.number_field :minute, in: 0..59, step: 1 %><br>
  <label>Second: </label>
  <%= f.number_field :second, in: 0..59, step: 1 %>

  <%= f.submit %>

<% end%>

app/views/users/index.html.erb
<%= render '/layouts/header'%>
<h3>All Users:</h3>
<% @user.each do |x| %>
  <%= link_to x.name, user_path(x)%> <br>
<% end %>

app/views/users/login.html.erb
<%= render '/layouts/header'%>
<% if flash[:notice] %>
  <br><h4><%= flash[:notice] %></h4>
  <% flash[:notice] = nil %>
<% end %>

<h2>Log In</h2>

<%= form_tag '/login' do %>
  Username: <%= text_field_tag :name %><br>
  Password: <%=password_field_tag :password %><br>
  <%= submit_tag "Log In"%>
<% end %>

app/views/users/new.html.erb
<%= render '/layouts/header'%>
<h2>Sign Up:</h2>

<%= form_for @user, url: postsignup_url do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being created:</h4>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <label>Name: </label>
    <%= f.text_field :name, required: true %><br>
  <label>Password: </label>
    <%= f.password_field :password, required: true %><br>
  <label>Confirm Password: </label>
    <%= f.password_field :password_confirmation, required: true %><br>

  <%= f.submit %>

<% end%>

app/views/users/show.html.erb
<%= render '/layouts/header'%>
<h3><%= @user.name %>'s runs</h3>

<% @user.games.uniq.each do |x|%>
  <h4><%= x.name %></h4>
  <% x.runs.order(:hour).order(:minute).order(:second).each do |y| %>
    <% if y.user_id.to_i == @user.id.to_i %>
    <h5> <%= y.time_formatting %></h5>
    <% end %>
  <% end %>

<% end %>